/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 balloon.glb 
Author: Styro (https://sketchfab.com/Styro4)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hot-air-balloon-low-poly-a420e9196b744919806ae532b3a11bf7
Title: Hot Air Balloon - Low Poly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Balloon(props) {
  const { nodes, materials } = useGLTF('/glbs/balloon.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Hot_Air_Balloon_Material001_0.geometry} material={materials['Material.001']} position={[0, 57.838, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[25.874, 25.874, 19.525]} />
      </group>
    </group>
  )
}

useGLTF.preload('/glbs/balloon.glb')
