/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 tavern.glb 
Author: EddyNL (https://sketchfab.com/EddyNL)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medieval-fantasy-tavern-eea5d10fea01404587a1b5703784bb0b
Title: Medieval Fantasy Tavern
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { MathUtils } from 'three'
import { useFrame } from '@react-three/fiber'
import { useLoaded } from '@/store';

export function Tavern({pointer}) {
  const group = useRef()
  const {  scene } = useGLTF('/glbs/mill.glb')

//   const [loaded, setLoaded] = useLoaded((state) => [
//     state.loaded,
//     state.setLoaded,
//   ]);



// useEffect(() => {
//   if( scene ){
//    setTimeout(() =>{
//     console.log("LOADED")
//     setLoaded(true)
//    },2000)
//   }
// },[])

  useFrame((state, delta) => {
  if(group.current && pointer){
  
    group.current.rotation.y = MathUtils.damp(group.current.rotation.y, (pointer.x* Math.PI) / 2, 5, delta);
    group.current.rotation.x = MathUtils.damp(group.current.rotation.x, (-pointer.y * Math.PI) / 12, 0.9, delta);
  }})

  return (
    <group ref={group}  dispose={null} position={[0,-0.5,-3.5]} rotation={[0,0.8,0]} scale={1}>
    <primitive object={scene} />
    </group>
  )
}

useGLTF.preload('/glbs/mill.glb')
