import React, { useRef, useMemo } from 'react';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import * as THREE from 'three';

const vertexShader = `
  varying vec2 vUv;
  void main() {
    vUv = uv;
    gl_Position = vec4(position, 1.0);
  }
`;

const fragmentShader = `
  precision highp float;

  uniform float uTime;
  uniform vec2 uResolution;
  uniform vec2 uMouse;

  varying vec2 vUv;

  // ─── Palette ────────────────────────────────────────────────────────────────
  #define VOID      vec3(0.000, 0.039, 0.020)
  #define DEEP      vec3(0.000, 0.200, 0.133)
  #define MID       vec3(0.000, 0.400, 0.267)
  #define LUMINOUS  vec3(0.200, 0.667, 0.467)
  #define HIGHLIGHT vec3(0.600, 1.000, 0.800)

  // ─── Noise / Hash ──────────────────────────────────────────────────────────
  float hash(vec2 p) {
    p = fract(p * vec2(234.34, 435.345));
    p += dot(p, p + 34.23);
    return fract(p.x * p.y);
  }

  float noise(vec2 p) {
    vec2 i = floor(p);
    vec2 f = fract(p);
    f = f * f * (3.0 - 2.0 * f);
    return mix(
      mix(hash(i + vec2(0.0,0.0)), hash(i + vec2(1.0,0.0)), f.x),
      mix(hash(i + vec2(0.0,1.0)), hash(i + vec2(1.0,1.0)), f.x),
      f.y
    );
  }

  float fbm(vec2 p) {
    float v = 0.0;
    float a = 0.5;
    for (int i = 0; i < 5; i++) {
      v += a * noise(p);
      p *= 2.0;
      a *= 0.5;
    }
    return v;
  }

  // ─── Angular ring fragmentation ────────────────────────────────────────────
  float angularGaps(float angle, float t, float radius) {
    float n = fbm(vec2(angle * 3.0 + t * 0.1, radius * 0.5));
    // Sparse gaps — most of the ring is missing
    n = pow(n, 1.8);
    return smoothstep(0.35, 0.65, n);
  }

  // ─── Single ring at radius r ───────────────────────────────────────────────
  float ring(float dist, float r, float thickness) {
    return smoothstep(thickness, 0.0, abs(dist - r));
  }

  void main() {
    vec2 uv = vUv;
    // Aspect-correct center
    vec2 center = vec2(0.5, 0.5);
    vec2 aspect = vec2(uResolution.x / uResolution.y, 1.0);
    vec2 pos = (uv - center) * aspect;
    float dist = length(pos);

    float t = uTime;

    // ── Background void ───────────────────────────────────────────────────────
    vec3 col = VOID;

    // Very subtle radial lift at edges — gives the void some depth
    col = mix(col, DEEP, smoothstep(0.3, 1.0, dist) * 0.6);

    // ── The center point — perfectly still ────────────────────────────────────
    float centerPulse = 0.8 + 0.2 * sin(t * 0.18);
    float centerGlow = exp(-dist * 18.0) * centerPulse;
    col += HIGHLIGHT * centerGlow * 0.7;

    // Small dense core
    float core = exp(-dist * 90.0) * centerPulse;
    col += HIGHLIGHT * core * 1.5;

    // ── Mouse influence on center — subtle warmth when hovered ───────────────
    vec2 mouseOffset = (uv - center) * aspect;
    float mouseDist = length(mouseOffset - (uMouse - 0.5) * aspect);
    float mouseHover = exp(-mouseDist * 6.0) * 0.15;
    col += LUMINOUS * mouseHover * centerPulse;

    // ── Concentric rings expanding outward from center ───────────────────────
    // Rings are generated by offsetting radial distance with time
    // Spacing increases with radius (organic, not mechanical)
    float numRings = 28.0;
    float slowestTime = t * 0.12; // very slow expansion

    for (float i = 0.0; i < numRings; i++) {
      // Each ring starts at center and expands
      // Spacing: tighter near center, wider toward periphery
      float spacingBias = 0.06 + i * 0.018;
      float ringRadius = mod(slowestTime + i * spacingBias, 0.9) * 1.1;

      if (ringRadius < 0.02) continue;

      // Irregular ring — not solid
      float angle = atan(pos.y, pos.x);
      float ringMask = angularGaps(angle, t, ringRadius);

      if (ringMask < 0.05) continue;

      // Ring alpha — fades as it expands
      float age = slowestTime + i * spacingBias;
      float ringAlpha = 1.0 - fract(age);
      ringAlpha = pow(ringAlpha, 1.5);

      // Thin rings
      float r = ring(dist, ringRadius, 0.004);

      // Color: luminous near center, deeper toward edge
      float colorT = smoothstep(0.0, 0.8, ringRadius);
      vec3 ringColor = mix(LUMINOUS, DEEP, colorT);

      col += ringColor * r * ringMask * ringAlpha * 0.5;
    }

    // ── Periphery — movement only out here ──────────────────────────────────
    float peripheryStart = 0.35;
    float peripheryStrength = smoothstep(peripheryStart, 1.0, dist);

    if (peripheryStrength > 0.0) {
      // Slow FBM drift — feels like breathing, not mechanical
      vec2 driftUV = pos * 2.5;
      float driftX = fbm(driftUV + vec2(t * 0.04, 0.0));
      float driftY = fbm(driftUV + vec2(0.0, t * 0.03 + 1.7));
      vec2 drift = (vec2(driftX, driftY) - 0.5) * 0.06 * peripheryStrength;

      float dDist = length(pos + drift);
      float dAngle = atan(pos.y + drift.y, pos.x + drift.x);

      // Periphery rings — more fragmented, branching
      float periRings = 14.0;
      float periTime = t * 0.09;

      for (float i = 0.0; i < periRings; i++) {
        float spacingBias = 0.08 + i * 0.025;
        float rRadius = mod(periTime + i * spacingBias, 0.85) * 1.15;

        if (rRadius < 0.01) continue;

        float angle = atan(pos.y + drift.y, pos.x + drift.x);
        float ringMask = angularGaps(angle * 0.7 + t * 0.05, t * 0.5, rRadius);

        if (ringMask < 0.03) continue;

        float age = periTime + i * spacingBias;
        float rAlpha = (1.0 - fract(age)) * 0.6;
        rAlpha *= peripheryStrength;

        float r = ring(dDist, rRadius, 0.006 + peripheryStrength * 0.008);
        vec3 rCol = mix(DEEP, MID, fbm(vec2(dAngle * 2.0, t * 0.1))) * peripheryStrength;

        col += rCol * r * ringMask * rAlpha * 0.35;

        // Branching tendrils — thin lines extending from ring fragments
        float tendrilNoise = fbm(vec2(dAngle * 8.0 + i, rRadius * 12.0 + t * 0.06));
        if (tendrilNoise > 0.62) {
          float tendrilDist = abs(dDist - rRadius);
          float tendril = smoothstep(0.012, 0.0, tendrilDist) * (tendrilNoise - 0.62) * 2.6;
          vec3 tCol = mix(MID, LUMINOUS, tendrilNoise) * peripheryStrength;
          col += tCol * tendril * ringMask * rAlpha * 0.4;
        }
      }

      // Peripheral void breathing — slow pulse in the dark edges
      float edgeBreath = fbm(pos * 1.2 + t * 0.02) * peripheryStrength;
      col += MID * edgeBreath * 0.06;
    }

    // ── Radial unity glow from center ─────────────────────────────────────────
    float unityGlow = exp(-dist * 2.5) * 0.03 * centerPulse;
    col += HIGHLIGHT * unityGlow;

    // ── Vignette ──────────────────────────────────────────────────────────────
    float vignette = 1.0 - smoothstep(0.4, 1.2, dist);
    col *= vignette;

    // ── Subtle chromatic aberration at extreme periphery ─────────────────────
    float aberration = peripheryStrength * 0.004;
    // Approximated: slight color shift in the final color
    col.r *= 1.0 + aberration;
    col.b *= 1.0 - aberration * 0.5;

    gl_FragColor = vec4(col, 1.0);
  }
`;

function ShaderScene() {
  const meshRef = useRef<THREE.Mesh>(null);
  const { size, viewport } = useThree();

  const uniforms = useMemo(
    () => ({
      uTime: { value: 0 },
      uResolution: { value: new THREE.Vector2(size.width, size.height) },
      uMouse: { value: new THREE.Vector2(0.5, 0.5) },
      uDate: { value: new THREE.Vector4() },
    }),
    [size.width, size.height]
  );

  useFrame((state) => {
    const mat = meshRef.current?.material as THREE.ShaderMaterial;
    if (!mat) return;
    mat.uniforms.uTime.value = state.clock.elapsedTime;
    mat.uniforms.uResolution.value.set(size.width, size.height);
    // Normalize mouse to [0,1]
    mat.uniforms.uMouse.value.set(
      state.mouse.x * 0.5 + 0.5,
      state.mouse.y * 0.5 + 0.5
    );
    const d = new Date();
    mat.uniforms.uDate.value.set(d.getFullYear(), d.getMonth() + 1, d.getDate(), d.getHours() * 3600 + d.getMinutes() * 60 + d.getSeconds());
  });

  return (
    <mesh ref={meshRef}>
      <planeGeometry args={[viewport.width, viewport.height]} />
      <shaderMaterial
        vertexShader={vertexShader}
        fragmentShader={fragmentShader}
        uniforms={uniforms}
        depthWrite={false}
        depthTest={false}
      />
    </mesh>
  );
}

const TendernessAtTheVoid: React.FC = () => {
  return (
    <Canvas
      style={{ background: '#000a05' }}
      camera={{ position: [0, 0, 1] }}
      gl={{ antialias: false, alpha: false }}
      dpr={Math.min(window.devicePixelRatio, 2)}
    >
      <ShaderScene />
    </Canvas>
  );
};

export default TendernessAtTheVoid;